title: Valid Users Failing to Authenticate From Single Source Using Kerberos
id: 5d1d946e-32e6-4d9a-a0dc-0ac022c7eb98
description: Detects multiple failed logins with multiple valid domain accounts from a single source system using the Kerberos protocol.
status: experimental
author: Mauricio Velazco, frack113
date: 2021/06/01
modified: 2021/07/06
references:
    - https://docs.splunk.com/Documentation/ESSOC/3.22.0/stories/UseCase#Active_directory_password_spraying
tags:
    - attack.t1110.003
    - attack.initial_access
    - attack.privilege_escalation
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 4771
        Status: '0x18'
    filter_computer:
        TargetUserName|endswith: '$'
    timeframe: 24h
    condition:
        - selection and not filter_computer
falsepositives:
    - Vulnerability scanners
    - Misconfigured systems
    - Remote administration tools
    - VPN terminators
    - Multiuser systems like Citrix server farms
level: medium
