title: Persistence and Execution at Scale via GPO Scheduled Task
id: a8f29a7b-b137-4446-80a0-b804272f3da2
status: test
description: Detect lateral movement using GPO scheduled task, usually used to deploy ransomware at scale
author: Samir Bousseaden
references:
  - https://twitter.com/menasec1/status/1106899890377052160
  - https://www.secureworks.com/blog/ransomware-as-a-distraction
date: 2019/04/03
modified: 2021/11/27
logsource:
  product: windows
  service: security
  definition: 'The advanced audit policy setting "Object Access > Audit Detailed File Share" must be configured for Success/Failure'
detection:
  selection:
    EventID: 5145
    ShareName: \\\*\SYSVOL
    RelativeTargetName|endswith: 'ScheduledTasks.xml'
    Accesses|contains:
      - 'WriteData'
      - '%%4417'
  condition: selection
falsepositives:
  - If the source IP is not localhost then it's super suspicious, better to monitor both local and remote changes to GPO scheduledtasks
level: high
tags:
  - attack.persistence
  - attack.lateral_movement
  - attack.t1053.005
