codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"
  status:
    project:
      default:
        target: 75%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
