title: DNS Query for Ufile.io Upload Domain
id: 1cbbeaaf-3c8c-4e4c-9d72-49485b6a176b
description: Detects DNS queries for subdomains used for upload to ufile.io
status: experimental
date: 2022/06/23
author: yatinwad and TheDFIRReport
references:
    - https://thedfirreport.com/2021/12/13/diavol-ransomware/
logsource:
    product: windows
    category: dns_query
detection:
    selection:
        QueryName|contains: ufile.io
    condition: selection
tags:
    - attack.exfiltration
    - attack.t1567.002
falsepositives:
    - Legitimate Ufile upload
level: high
