title: Windows Defender Firewall Has Been Reset To Its Default Configuration
id: 04b60639-39c0-412a-9fbe-e82499c881a3
status: experimental
description: Detects activity when Windows Defender Firewall has been reset to its default configuration
references:
    - https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd364427(v=ws.10)
author: frack113
date: 2022/02/19
modified: 2023/01/17
logsource:
    product: windows
    service: firewall-as
detection:
    selection:
        EventID: 2032 # Windows Defender Firewall has been reset to its default configuration
    condition: selection
level: low
