title: Possible Process Hollowing Image Loading
id: e32ce4f5-46c6-4c47-ba69-5de3c9193cd7
status: test
description: Detects Loading of samlib.dll, WinSCard.dll from untypical process e.g. through process hollowing by Mimikatz
author: Markus Neis
references:
  - https://cyberwardog.blogspot.com/2017/03/chronicles-of-threat-hunter-hunting-for.html
date: 2018/01/07
modified: 2021/11/27
logsource:
  category: image_load
  product: windows
detection:
  selection:
    Image|endswith: 'notepad'
    ImageLoaded|endswith:
      - 'samlib'
      - 'WinSCard'
  condition: selection
falsepositives:
  - Very likely, needs more tuning
level: high
tags:
  - attack.defense_evasion
  - attack.t1574.002
