title: Suspicious Set Value of MSDT in Registry (CVE-2022-30190)
id: 2d9403d5-7927-46b7-8216-37ab7c9ec5e3
status: experimental
description: Detects set value ms-msdt MSProtocol URI scheme in Registry that could be an attempt to exploit CVE-2022-30190.
author: Sittikorn S
references:
  - https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-30190
  - https://msrc-blog.microsoft.com/2022/05/30/guidance-for-cve-2022-30190-microsoft-support-diagnostic-tool-vulnerability/
date: 2020/05/31
logsource:
  product: windows
  category: registry_set
detection:
  selection:
    EventType: SetValue
    TargetObject|startswith: 'HKCR\ms-msdt\'
  condition: selection
falsepositives:
  - Unknown
level: medium
tags:
  - attack.defense_evasion
  - attack.t1221
