title: Disable Internal Tools or Feature in Registry
id: e2482f8d-3443-4237-b906-cc145d87a076
status: experimental
description: Detects registry modifications that change features of internal Windows tools (malware like Agent Tesla uses this technique)
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1112/T1112.md
    - https://www.mandiant.com/resources/unc2165-shifts-to-evade-sanctions
author: frack113, Nasreddine Bencherchali
date: 2022/03/18
modified: 2022/06/03
logsource:
    category: registry_set
    product: windows
detection:
    selection_set_1:
        EventType: SetValue
        TargetObject|endswith:
            - 'SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\system\DisableRegistryTools'
            - 'SOFTWARE\Policies\Microsoft\Windows\System\DisableCMD'
            - 'SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\system\DisableTaskmgr'
            - 'SOFTWARE\Policies\Microsoft\Windows\Explorer\DisableNotificationCenter'
            - 'SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\DisableChangePassword'
            - 'SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\DisableLockWorkstation'
            - 'SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\StartMenuLogOff'
        Details: 'DWORD (0x00000001)'
    selection_set_0:
        EventType: SetValue
        TargetObject|endswith:
            - 'SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\shutdownwithoutlogon'
            - 'SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications\ToastEnabled'
            - '\SYSTEM\CurrentControlSet\Control\Storage\Write Protection'
            - '\SYSTEM\CurrentControlSet\Control\StorageDevicePolicies\WriteProtect'
        Details: 'DWORD (0x00000000)'
    condition: 1 of selection_set_*
falsepositives:
    - Legitimate admin script
level: medium
tags:
    - attack.defense_evasion
    - attack.t1112
