title: Browser Credential Store Access
id: 91cb43db-302a-47e3-b3c8-7ede481e27bf
status: experimental
description: Detects suspicious processes based on name and location that access the browser credential stores which can be the sign of credential stealing
references:
    - https://www.zscaler.com/blogs/security-research/ffdroider-stealer-targeting-social-media-platform-users
    - https://github.com/lclevy/firepwd
author: frack113
date: 2022/04/09
modified: 2022/06/29
tags:
    - attack.t1003
    - attack.credential_access
logsource:
    category: file_access
    product: windows
detection:
    selection:
        - FileName|contains:
            - '\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies'
            - '\Appdata\Local\Chrome\User Data\Default\Login Data'
            - '\AppData\Local\Google\Chrome\User Data\Local State'
        - FileName|endswith:
            - '\Appdata\Local\Microsoft\Windows\WebCache\WebCacheV01.dat'
            - '\cookies.sqlite'
            - 'release\key3.db'  #firefox
            - 'release\key4.db'  #firefox
            - 'release\logins.json' #firefox
    filter_browser:
        Image|endswith:
            - '\firefox.exe'
            - '\chrome.exe'
    filter_programfile:
        Image|startswith:
            - 'C:\Program Files\'
            - 'C:\Program Files (x86)\'
            - 'C:\WINDOWS\system32\'
    filter_antimalware:
        Image|endswith:
            - '\MsMpEng.exe'
            - '\MpCopyAccelerator.exe'
    condition: selection and not 1 of filter_*
falsepositives:
    - Antivirus, Anti-Spyware, Anti-Malware Software
    - Backup software
level: medium
