title: Azure Subscription Permission Elevation Via ActivityLogs
id: 09438caa-07b1-4870-8405-1dbafe3dad95
status: experimental
author: Austin Songer @austinsonger
date: 2021/11/26
description: Detects when a user has been elevated to manage all Azure Subscriptions. This change should be investigated immediately if it isn't planned. This setting could allow an attacker access to Azure subscriptions in your environment.
references:
  - https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftauthorization
logsource:
  product: azure
  service: activitylogs
detection:
    selection1:
        properties.message: MICROSOFT.AUTHORIZATION/ELEVATEACCESS/ACTION
    condition: selection1
level: high
falsepositives:
  - If this was approved by System Administrator.
tags:
  - attack.initial_access
  - attack.t1078
