title: Use of Wfc.exe
id: 49be8799-7b4d-4fda-ad23-cafbefdebbc5
status: experimental
description: The Workflow Command-line Compiler can be used for AWL bypass and is listed in Microsoft's recommended block rules.
author: 'Christopher Peacock @SecurePeacock, SCYTHE @scythe_io'
references:
  - https://lolbas-project.github.io/lolbas/OtherMSBinaries/Wfc/
  - https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules
date: 2022/06/01
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    - Image|endswith: '\wfc.exe'
    - OriginalFileName: 'wfc.exe'
  condition: selection
falsepositives:
  - Legitimate use by a software developer
level: medium
tags:
  - attack.defense_evasion
  - attack.t1127
