title: Judgement Panda Exfil Activity
id: 03e2746e-2b31-42f1-ab7a-eb39365b2422
status: test
description: Detects Judgement Panda activity as described in Global Threat Report 2019 by Crowdstrike
author: Florian Roth
references:
  - https://www.crowdstrike.com/resources/reports/2019-crowdstrike-global-threat-report/
date: 2019/02/21
modified: 2021/11/27
logsource:
  category: process_creation
  product: windows
detection:
  selection1:
    - CommandLine|endswith: 'eprod.ldf'
    - CommandLine|contains:
      - '\ldifde.exe -f -n '
      - '\7za.exe a 1.7z '
      - '\aaaa\procdump64.exe'
      - '\aaaa\netsess.exe'
      - '\aaaa\7za.exe'
      - 'copy .\1.7z \'
      - 'copy \\client\c$\aaaa\'
  selection2:
    Image: C:\Users\Public\7za.exe
  condition: selection1 or selection2
falsepositives:
  - Unknown
level: critical
tags:
  - attack.lateral_movement
  - attack.g0010
  - attack.credential_access
  - attack.t1003.001
  - attack.exfiltration
  - attack.t1560.001
