title: Curl Start Combination
id: 21dd6d38-2b18-4453-9404-a0fe4a0cc288
status: test
description: Adversaries can use curl to download payloads remotely and execute them. Curl is included by default in Windows 10 build 17063 and later.
author: Sreeman
references:
  - https://medium.com/@reegun/curl-exe-is-the-new-rundll32-exe-lolbin-3f79c5f35983
date: 2020/01/13
modified: 2022/07/05
logsource:
  category: process_creation
  product: windows
detection:
  selection_curl:
    - Image|endswith: '\curl.exe'
    - Product: 'The curl executable'
  selection_susp_flags:
    CommandLine|contains:
      - ' start '
      - '&call '
      - '& call '
  condition: all of selection*
fields:
  - ParentImage
  - CommandLine
falsepositives:
  - Administrative scripts (installers)
level: high
tags:
  - attack.execution
  - attack.t1218
  - attack.command_and_control
  - attack.t1105
