title: Java Running with Remote Debugging
id: 8f88e3f6-2a49-48f5-a5c4-2f7eedf78710
status: test
description: Detects a JAVA process running with remote debugging allowing more than just localhost to connect
author: Florian Roth
date: 2019/01/16
modified: 2021/11/27
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    CommandLine|contains: 'transport=dt_socket,address='
  exclusion:
    - CommandLine|contains: 'address=127.0.0.1'
    - CommandLine|contains: 'address=localhost'
  condition: selection and not exclusion
fields:
  - CommandLine
  - ParentCommandLine
falsepositives:
  - Unknown
level: medium
tags:
  - attack.t1203
  - attack.execution
