title: Suspicious Bitsadmin Job via PowerShell
id: f67dbfce-93bc-440d-86ad-a95ae8858c90
status: test
description: Detect download by BITS jobs via PowerShell
author: Endgame, JHasenbusch (ported to sigma for oscd.community)
references:
  - https://eqllib.readthedocs.io/en/latest/analytics/ec5180c9-721a-460f-bddc-27539a284273.html
  - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1197/T1197.md
date: 2018/10/30
modified: 2021/12/03
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image|endswith: '\powershell.exe'
    CommandLine|contains: 'Start-BitsTransfer'
  condition: selection
fields:
  - ComputerName
  - User
  - CommandLine
falsepositives:
  - Unknown
level: high
tags:
  - attack.defense_evasion
  - attack.persistence
  - attack.t1197
