title: Run PowerShell Script from ADS
id: 45a594aa-1fbd-4972-a809-ff5a99dd81b8
status: test
description: Detects PowerShell script execution from Alternate Data Stream (ADS)
author: Sergey Soldatov, Kaspersky Lab, oscd.community
references:
  - https://github.com/p0shkatz/Get-ADS/blob/master/Get-ADS.ps1
date: 2019/10/30
modified: 2021/11/27
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    ParentImage|endswith: '\powershell.exe'
    Image|endswith: '\powershell.exe'
    CommandLine|contains|all:
      - 'Get-Content'
      - '-Stream'
  condition: selection
falsepositives:
  - Unknown
level: high
tags:
  - attack.defense_evasion
  - attack.t1564.004
