title: Suspicious PowerShell Sub Processes
id: e4b6d2a7-d8a4-4f19-acbd-943c16d90647
description: Detects suspicious sub processes spawned by PowerShell
status: experimental
author: Florian Roth
date: 2022/04/26
references:
    - https://twitter.com/ankit_anubhav/status/1518835408502620162
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        ParentImage|endswith: '\powershell.exe'
        Image|endswith:
            - '\sh.exe'
            - '\bash.exe'
            - '\schtasks.exe'
            - '\certutil.exe'
            - '\bitsadmin.exe'
            - '\wscript.exe'
            - '\cscript.exe'
            - '\scrcons.exe'
            - '\regsvr32.exe'
            - '\hh.exe'
            - '\wmic.exe'
            - '\mshta.exe'
            - '\rundll32.exe'
            - '\forfiles.exe'
            - '\scriptrunner.exe'
    condition: selection
falsepositives:
    - Unknown
level: high
