title: Use of OpenConsole
id: 814c95cc-8192-4378-a70a-f1aafd877af1
description: Detects usage of OpenConsole binary as a LOLBIN to launch other binaries to bypass application Whitelisting
status: experimental
references:
    - https://twitter.com/nas_bench/status/1537563834478645252
author: Nasreddine Bencherchali
date: 2022/06/16
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        - OriginalFileName: 'OpenConsole.exe'
        - Image|endswith: '\OpenConsole.exe'
    filter:
        Image|startswith: 'C:\Program Files\WindowsApps\Microsoft.WindowsTerminal' # We exclude the default path for WindowsTerminal
    condition: selection and not filter
falsepositives:
    - Legitimate use by an administrator
level: medium
tags:
    - attack.execution
    - attack.t1059
