title: Suspicious Extrac32 Execution
id: aa8e035d-7be4-48d3-a944-102aec04400d
status: experimental
description: Download or Copy file with Extrac32
references:
    - https://lolbas-project.github.io/lolbas/Binaries/Extrac32/
tags:
    - attack.command_and_control
    - attack.t1105
author: frack113
date: 2021/11/26
modified: 2022/05/16
logsource:
    category: process_creation
    product: windows
detection:
    selection_lolbas:
        - CommandLine|contains: extrac32.exe
        - Image|endswith: '\extrac32.exe'
        - OriginalFileName: 'extrac32.exe'
    selection_archive:
       ommandLine|contains: '.cab'
    selection_options:
       CommandLine|contains:
            - /C
            - /Y
            - ' \\'
    condition: all of selection_*
falsepositives:
    - Unknown
level: medium
