title: CL_Mutexverifiers.ps1 Proxy Execution
id: 1e0e1a81-e79b-44bc-935b-ddb9c8006b3d
description: Detects the use of a Micorsoft signed script to execute commands
status: experimental
references:
    - https://lolbas-project.github.io/lolbas/Scripts/CL_mutexverifiers/
author: oscd.community, Natalia Shornikova, frack113
date: 2022/05/21
modified: 2022/06/28
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        CommandLine|contains|all:
            - '\CL_Mutexverifiers.ps1'
            - 'runAfterCancelProcess '
    condition: selection
falsepositives:
    - Unknown
level: medium
tags:
    - attack.defense_evasion
    - attack.t1216
