title: UAC Bypass Tool UACMe
id: d38d2fa4-98e6-4a24-aff1-410b0c9ad177
description: Detects execution of UACMe (a tool used for UAC bypass) via default PE metadata
author: Christian Burkard
date: 2021/08/30
status: experimental
references:
    - https://github.com/hfiref0x/UACME
tags:
    - attack.defense_evasion
    - attack.privilege_escalation
    - attack.t1548.002
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        - Product: 'UACMe'
        - Company: 'REvol Corp'
        - OriginalFileName: 'Akagi.exe'
    condition: selection
falsepositives:
    - Unknown
level: high
