title: Compress Data and Lock With Password for Exfiltration With 7-ZIP
id: 9fbf5927-5261-4284-a71d-f681029ea574
status: experimental
author: frack113
date: 2021/07/27
modified: 2021/12/02
description: An adversary may compress or encrypt data that is collected prior to exfiltration using 3rd party utilities
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1560.001/T1560.001.md
tags:
    - attack.collection
    - attack.t1560.001
logsource:
    category: process_creation
    product: windows
detection:
    selection_7z:
        CommandLine|contains:
            - '7z.exe'
            - '7za.exe'
    selection_password:
        CommandLine|contains: ' -p'
    selection_action:
        CommandLine|contains:
            - ' a '
            - ' u '
    condition: all of selection*
falsepositives:
    - Command line parameter combinations that contain all included strings
level: medium
fields:
    - CommandLine
    - ParentCommandLine
    - CurrentDirectory
