title: High Integrity Sdclt Process
id: 40f9af16-589d-4984-b78d-8c2aec023197
status: test
description: A General detection for sdclt being spawned as an elevated process. This could be an indicator of sdclt being used for bypass UAC techniques.
author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
references:
  - https://github.com/OTRF/detection-hackathon-apt29/issues/6
  - https://threathunterplaybook.com/evals/apt29/detections/3.B.2_C36B49B5-DF58-4A34-9FE9-56189B9DEFEA.html
date: 2020/05/02
modified: 2021/11/27
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image|endswith: 'sdclt.exe'
    IntegrityLevel: 'High'
  condition: selection
falsepositives:
  - Unknown
level: medium
tags:
  - attack.privilege_escalation
  - attack.defense_evasion
  - attack.t1548.002
