title: WMI Remote Command Execution
id: e42af9df-d90b-4306-b7fb-05c863847ebd
status: experimental
description: An adversary might use WMI to execute commands on a remote system
author: frack113
references:
    - https://securelist.com/moonbounce-the-dark-side-of-uefi-firmware/105468/
    - https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wmic
date: 2022/03/13
modified: 2022/05/13
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        - Image|endswith: \WMIC.exe
        - OriginalFileName: 'wmic.exe'
    selection_cli:
        CommandLine|contains|all:
            - '/node:'
            - process
            - call
            - create
    condition: all of selection*
falsepositives:
    - Unknown
level: medium
tags:
    - attack.execution
    - attack.t1047
