title: Suspicious Sc Query
id: 57712d7a-679c-4a41-a913-87e7175ae429
status: experimental
description: Adversaries may try to get information about registered services
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1007/T1007.md#atomic-test-1---system-service-discovery
author: frack113
date: 2021/12/06
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        CommandLine|contains: 'sc query'
    condition: selection
falsepositives:
    - Unknown
level: low
tags:
    - attack.discovery
    - attack.t1007
