title: New Service Creation
id: 7fe71fc9-de3b-432a-8d57-8c809efc10ab
status: test
description: Detects creation of a new service.
author: Timur Zinniatullin, Daniil Yugoslavskiy, oscd.community
references:
  - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1543.003/T1543.003.md
date: 2019/10/21
modified: 2021/11/27
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    - Image|endswith: '\sc.exe'
      CommandLine|contains|all:
        - 'create'
        - 'binpath'
    - Image|endswith: '\powershell.exe'
      CommandLine|contains: 'new-service'
  condition: selection
falsepositives:
  - Legitimate administrator or user creates a service for legitimate reasons.
level: low
tags:
  - attack.persistence
  - attack.privilege_escalation
  - attack.t1543.003
