title: WMIC Service Start/Stop
id: 0b7163dc-7eee-4960-af17-c0cd517f92da
status: experimental
description: Detects usage of wmic to start or stop a service
author: Nasreddine Bencherchali
references:
    - https://sushant747.gitbooks.io/total-oscp-guide/content/privilege_escalation_windows.html
date: 2022/06/20
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        - OriginalFileName: 'wmic.exe'
        - Image|endswith: '\WMIC.exe'
    selection_cli:
        CommandLine|contains|all:
            - ' service '
            - ' call '
        CommandLine|contains:
            - 'stopservice'
            - 'startservice'
    condition: all of selection*
falsepositives:
    - Unknown
level: medium
tags:
    - attack.execution
    - attack.t1047
