title: Use of Mftrace.exe
id: 3d48c9d3-1aa6-418d-98d3-8fd3c01a564e
status: experimental
description: The "Trace log generation tool for Media Foundation Tools" (Mftrace.exe) can be used to execute arbitrary binaries
author: Nasreddine Bencherchali
references:
    - https://lolbas-project.github.io/lolbas/OtherMSBinaries/Mftrace/
date: 2022/06/09
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        - Image|endswith: '\mftrace.exe'
        - OriginalFileName: 'mftrace.exe'
    selection_cli:
        # This assumes that when someone use mftrace to launch an ".exe" he will add a space and the binary launched will end with ".exe"
        CommandLine|contains: '.exe '
        CommandLine|endswith: '.exe'
    parent:
        ParentImage|endswith: '\mftrace.exe'
    condition: all of selection* or parent
falsepositives:
  - Legitimate use for tracing purposes
level: medium
tags:
    - attack.defense_evasion
    - attack.t1127
