title: Hiding Files with Attrib.exe
id: 4281cb20-2994-4580-aa63-c8b86d019934
status: test
description: Detects usage of attrib.exe to hide files from users.
author: Sami Ruohonen
date: 2019/01/16
modified: 2021/11/27
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image|endswith: '\attrib.exe'
    CommandLine|contains: ' +h '
  ini:
    CommandLine|contains: '\desktop.ini '
  intel:
    ParentImage|endswith: '\cmd.exe'
    CommandLine: +R +H +S +A \\*.cui
    ParentCommandLine: C:\WINDOWS\system32\\*.bat
  condition: selection and not (ini or intel)
fields:
  - CommandLine
  - ParentCommandLine
  - User
falsepositives:
  - IgfxCUIService.exe hiding *.cui files via .bat script (attrib.exe a child of cmd.exe and igfxCUIService.exe is the parent of the cmd.exe)
  - Msiexec.exe hiding desktop.ini
level: low
tags:
  - attack.defense_evasion
  - attack.t1564.001
