title: Windows Update Client LOLBIN
id: d7825193-b70a-48a4-b992-8b5b3015cc11
status: experimental
description: Detects code execution via the Windows Update client (wuauclt)
references:
    - https://dtm.uk/wuauclt/
author: FPT.EagleEye Team
date: 2020/10/17
modified: 2022/05/13
tags:
    - attack.command_and_control
    - attack.execution
    - attack.t1105
    - attack.t1218
logsource:
    product: windows
    category: process_creation
detection:
    selection_cli:
        CommandLine|contains|all:
            - '/UpdateDeploymentProvider'
            - '/RunHandlerComServer'
            - '.dll'
    selection_img:
        - Image|endswith: '\wuauclt.exe'
        - OriginalFileName: 'wuauclt.exe'
    filter:
        CommandLine|contains:
            - ' /ClassId '
            - ' wuaueng.dll '
    condition: all of selection* and not filter
falsepositives:
    - Unknown
level: high
