title: NirCmd Tool Execution
id: 4e2ed651-1906-4a59-a78a-18220fca1b22
status: experimental
description: Detects the use of NirCmd tool for command execution, which could be the result of legitimate administrative activity
author: 'Florian Roth, Nasreddine Bencherchali @nas_bench'
date: 2022/01/24
modified: 2022/05/13
references:
    - https://www.nirsoft.net/utils/nircmd.html
    - https://www.winhelponline.com/blog/run-program-as-system-localsystem-account-windows/
    - https://www.nirsoft.net/utils/nircmd2.html#using
tags:
    - attack.execution
    - attack.t1569.002
    - attack.s0029
logsource:
    category: process_creation
    product: windows
detection:
    selection_org:
        OriginalFileName: 'NirCmd.exe'
    combo_exec:
        CommandLine|contains:
            - ' exec '
            - ' exec2 '
    combo_exec_params:
        CommandLine|contains:
            - ' show '
            - ' hide '
    selection_cmd:
        CommandLine|contains:
            - ' execmd '
            - '.exe script '
            - '.exe shexec '
            - ' runinteractive '
    condition: 1 of selection* or (combo_exec and combo_exec_params)
fields:
    - CommandLine
    - ParentCommandLine
falsepositives:
    - Legitimate use by administrators
level: medium
