title: Application Whitelisting Bypass via PresentationHost.exe
id: d22e2925-cfd8-463f-96f6-89cec9d9bc5f
description: Detects usage of "PresentationHost" which is a utility that runs ".xbap" (Browser Applications) files. It can be abused to run malicious ".xbap" files any bypass AWL
status: experimental
references:
    - https://lolbas-project.github.io/lolbas/Binaries/Presentationhost/
author: Nasreddine Bencherchali
date: 2022/07/01
logsource:
    category: process_creation
    product: windows
detection:
    selection_img:
        - Image|endswith: '\presentationhost.exe'
        - OriginalFileName: 'PresentationHost.exe'
    selection_cli:
        CommandLine|contains: '.xbap'
    filter:
        CommandLine|contains: # Filter out legitimate locations if you find them
            - 'C:\Windows\'
            - 'C:\Program Files'
    condition: all of selection* and not filter
falsepositives:
    - Legitimate ".xbap" being executed via "PresentationHost"
level: medium
tags:
    - attack.defense_evasion
    - attack.execution
    - attack.t1218
