title: Bitsadmin Download to Uncommon Target Folder
id: 6e30c82f-a9f8-4aab-b79c-7c12bce6f248
status: experimental
description: Detects usage of bitsadmin downloading a file to uncommon target folder
references:
    - https://blog.netspi.com/15-ways-to-download-a-file/#bitsadmin
    - https://isc.sans.edu/diary/22264
    - https://lolbas-project.github.io/lolbas/Binaries/Bitsadmin/
tags:
    - attack.defense_evasion
    - attack.persistence
    - attack.t1197
    - attack.s0190
    - attack.t1036.003
date: 2022/06/28
author: Florian Roth
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith: '\bitsadmin.exe'
        CommandLine|contains:
            - ' /transfer '
            - ' /create '
            - ' /addfile '
    selection_folder:
        CommandLine|contains:
            - 'C:\Windows\Temp\'
            - '%temp%'
            - 'C:\ProgramData\'
            - '%ProgramData%'
            - '\AppData\Local\'
            - '%AppData%'
    condition: all of selection*
fields:
    - CommandLine
    - ParentCommandLine
falsepositives:
    - Unknown
level: medium
