title: Trickbot Malware Activity
id: 58bf96d9-ff5f-44bd-8dcc-1c4f79bf3a27
status: stable
description: Detects Trickbot malware process tree pattern in which rundll32.exe is parent of wermgr.exe
author: Florian Roth
references:
  - https://twitter.com/swisscom_csirt/status/1331634525722521602?s=20
  - https://app.any.run/tasks/f74c5157-8508-4ac6-9805-d63fe7b0d399/
date: 2020/11/26
modified: 2021/11/27
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image|endswith: '\wermgr.exe'
    ParentImage|endswith: '\rundll32.exe'
    ParentCommandLine|contains: 'DllRegisterServer'
  condition: selection
falsepositives:
  - Unknown
level: high
tags:
  - attack.execution
  - attack.t1559
