title: Mavinject Inject DLL Into Running Process
id: 4f73421b-5a0b-4bbf-a892-5a7fb99bea66
status: experimental
author: frack113
date: 2021/07/12
modified: 2022/05/13
description: Injects arbitrary DLL into running process specified by process ID. Requires Windows 10.
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1218/T1218.md
    - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1056.004/T1056.004.md
    - https://posts.specterops.io/mavinject-exe-functionality-deconstructed-c29ab2cf5c0e
tags:
    - attack.defense_evasion
    - attack.collection
    - attack.t1218.013
    - attack.t1056.004
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        CommandLine|contains|all:
            - ' /INJECTRUNNING'
            - '.dll' # space some time in the end
        OriginalFileName:
            - 'mavinject32.exe'
            - 'mavinject64.exe'
    condition: selection
fields:
    - ComputerName
    - User
    - CommandLine
    - ParentCommandLine
falsepositives:
    - Unknown
level: medium
