title: Creation In User Word Statup Folder
id: a10a2c40-2c4d-49f8-b557-1a946bc55d9d
status: experimental
description: Detects the creation of an file in user Word Startup
author: frack113
references:
  - Malware Sandbox https://app.any.run/tasks/d6fe6624-6ef8-485d-aa75-3d1bdda2a08c/
date: 2022/06/05
logsource:
  product: windows
  category: file_event
detection:
  selection:
    TargetFilename|contains: '\AppData\Roaming\Microsoft\Word\STARTUP\'
  filter_ext:
    TargetFilename|endswith:
      - '.docx' # Word document
      - '.docm' # Word macro-enabled document; same as docx, but may contain macros and scripts
      - '.dotx' # Word template
      - '.dotm' # Word macro-enabled template; same as dotx, but may contain macros and scripts
      - '.docb' # Word binary document introduced in Microsoft Office 2007
      - '.pdf'  # PDF documents
      - '.wll'  # Word add-in
      - '.wwl'  # Word add-in
  condition: selection and not filter_ext
falsepositives:
  - Addition of legitimate plugins
level: medium
tags:
  - attack.resource_development
  - attack.t1587.001
