title: Execution via CL_Mutexverifiers.ps1 (2 Lines)
id: 6609c444-9670-4eab-9636-fe4755a851ce
description: Detects Execution via runAfterCancelProcess in CL_Mutexverifiers.ps1 module
status: experimental
author: oscd.community, Natalia Shornikova
date: 2020/10/14
modified: 2021/10/16
references:
    - https://github.com/LOLBAS-Project/LOLBAS/blob/master/yml/OSScripts/CL_mutexverifiers.yml
    - https://twitter.com/pabraeken/status/995111125447577600
tags:
    - attack.defense_evasion
    - attack.t1216
logsource:
    product: windows
    category: ps_script
    definition: Script block logging must be enabled
detection:
    selection:
        ScriptBlockText|contains:
          - 'CL_Mutexverifiers.ps1'
          - 'runAfterCancelProcess'
    condition: selection
      # PS > Import-Module c:\Windows\diagnostics\system\Audio\CL_Mutexverifiers.ps1
      # PS > runAfterCancelProcess c:\Evil.exe
falsepositives:
    - Unknown
level: high
