title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION
id: e54f5149-6ba3-49cf-b153-070d24679126
description: Detects Obfuscated Powershell via VAR++ LAUNCHER
status: experimental
author: Timur Zinniatullin, oscd.community
date: 2020/10/13
modified: 2021/10/16
references:
    - https://github.com/Neo23x0/sigma/issues/1009 #(Task27)
tags:
    - attack.defense_evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
logsource:
    product: windows
    category: ps_script
    definition: Script block logging must be enabled
detection:
    selection_4104:
        ScriptBlockText|re: '(?i).*&&set.*(\{\d\}){2,}\\\"\s+?\-f.*&&.*cmd.*\/c' # FPs with |\/r
    condition: selection_4104
falsepositives:
    - Unknown
level: high
