title: Logon Scripts Creation in UserInitMprLogonScript Registry
id: 9ace0707-b560-49b8-b6ca-5148b42f39fb
status: test
description: Detects creation of UserInitMprLogonScript persistence method
author: Tom Ueltschi (@c_APT_ure)
references:
  - https://attack.mitre.org/techniques/T1037/
  - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1037.001/T1037.001.md
date: 2019/01/12
modified: 2022/06/26
logsource:
  category: registry_add
  product: windows
detection:
  selection:
    EventType: CreateKey
    TargetObject|contains: 'UserInitMprLogonScript'
  condition: selection
falsepositives:
  - Exclude legitimate logon scripts
level: high
tags:
  - attack.t1037.001
  - attack.persistence
  - attack.lateral_movement
